eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/netcorner/config.git
          search-paths:
          - demoConfig
      label: master
server:
  port: 8003